name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g serverless
        serverless plugin install -n serverless-python-requirements
    
    - name: Run SAST with Bandit
      run: |
        pip install bandit
        bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}" --exclude ./node_modules

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH

    - name: Run SCA with OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
      with:
        project: 'My Project'
        path: '.'
        format: 'HTML'
    

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/DevSecOpsChallengeRole
        role-session-name: GitHubActions

    - name: Deploy to AWS Lambda
      run: serverless deploy

    - name: Send findings to AWS Security Hub
      run: |
        # This is a simplified example. You'd need to format your findings to match Security Hub's format.
        aws securityhub batch-import-findings --findings file://findings.json
